const proyectos = [
  {
    id: 'proj-001',
    titulo: 'Migración a la Nube',
    descripcion: 'Mover todos los servicios del servidor local a una plataforma en la nube antes de fin de mes.',
    estado: 'En Progreso',
    responsables: [{ id: 'u1', nombre: 'Carlos' }, { id: 'u2', nombre: 'Beatriz' }],
    prioridad: 'Alta',
  },
  {
    id: 'proj-002',
    titulo: 'Rediseño Web',
    descripcion: 'Actualizar la interfaz de usuario y mejorar la accesibilidad del sitio corporativo.',
    estado: 'Pendiente',
    responsables: [{ id: 'u3', nombre: 'Ana' }],
    prioridad: 'Media',
  },
  {
    id: 'proj-003',
    titulo: 'Integración API Pagos',
    descripcion: 'Implementar la pasarela de pagos y pruebas E2E.',
    estado: 'En Progreso',
    responsables: [{ id: 'u4', nombre: 'Diego' }, { id: 'u5', nombre: 'Lucía' }],
    prioridad: 'Alta',
  },
  {
    id: 'proj-004',
    titulo: 'Campaña Marketing Q4',
    descripcion: 'Planificar y ejecutar campaña para la temporada de compras.',
    estado: 'Pendiente',
    responsables: [{ id: 'u6', nombre: 'María' }],
    prioridad: 'Media',
  },
  {
    id: 'proj-005',
    titulo: 'Auditoría de Seguridad',
    descripcion: 'Auditoría completa de infra y corrección de vulnerabilidades críticas.',
    estado: 'En Progreso',
    responsables: [{ id: 'u7', nombre: 'Andrés' }],
    prioridad: 'Alta',
  },
  {
    id: 'proj-006',
    titulo: 'Documentación Técnica',
    descripcion: 'Crear documentación interna para onboarding de nuevos desarrolladores.',
    estado: 'Completado',
    responsables: [{ id: 'u8', nombre: 'Paula' }],
    prioridad: 'Baja',
  },
  {
    id: 'proj-007',
    titulo: 'App Móvil (MVP)',
    descripcion: 'Entregar la versión mínima viable para pruebas de usuarios.',
    estado: 'Pendiente',
    responsables: [{ id: 'u9', nombre: 'Miguel' }, { id: 'u10', nombre: 'Laura' }],
    prioridad: 'Alta',
  },
  {
    id: 'proj-008',
    titulo: 'Optimización Base de Datos',
    descripcion: 'Reducir tiempos de consulta y optimizar índices.',
    estado: 'En Progreso',
    responsables: [{ id: 'u4', nombre: 'Diego' }],
    prioridad: 'Media',
  },
  {
    id: 'proj-009',
    titulo: 'Soporte SLA',
    descripcion: 'Mejorar los procesos para cumplir con el SLA del cliente X.',
    estado: 'Completado',
    responsables: [{ id: 'u2', nombre: 'Beatriz' }],
    prioridad: 'Media',
  },
  {
    id: 'proj-010',
    titulo: 'Automatización Tests',
    descripcion: 'Crear pipelines para ejecutar tests automatizados en CI.',
    estado: 'Pendiente',
    responsables: [{ id: 'u1', nombre: 'Carlos' }, { id: 'u5', nombre: 'Lucía' }],
    prioridad: 'Media',
  },
];

export default proyectos;
