import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
          <div className="container">
            <a className="navbar-brand" href="/">
              Cinema DB
            </a>

            <div className="navbar-nav">
              <a className="nav-link" href="/movies">
                Movies
              </a>

              <a className="nav-link" href="/actors">
                Actors
              </a>
            </div>
          </div>
        </nav>

        {children}
      </body>
    </html>
  );
}
